export interface fiotReading {
  channel: {
    id:number,
    name:string,
    description:string,
    latitude:string,
    longitude:string,
    field1:string,
    field2:string,
    field3:string,
    field4:string,
    field5:string,
    field6:string,
    created_at:string,
    updated_at:string,
    last_entry_id:string,
  },
  feeds: {
    0:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    1:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    2:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    3:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    4:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    5:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    6:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    7:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    8:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
    9:{
      created_at:string,
      entry_id:string,
      field1:string,
      field2:string,
      field3:string,
      field4:string,
      field5:string,
      field6:string,
    }
  }
}

/*
export interface fiotReading {
  temperature_value:number,
  humidity_value:number,
  pressure_value:number,
  leaf_wetness_value:number,
  soil_moisture_value:number,
  soil_temperature_value:number,
}
 */
